from flask_wtf import FlaskForm 
from wtforms import FloatField, PasswordField, SubmitField
from wtforms.validators import  DataRequired, Email

class TextForm(FlaskForm):
    meanradiusvalue = FloatField('Mean Radius', validators=[DataRequired()])
    meantexturevalue = FloatField('Mean Texture', validators=[DataRequired()])
    meanperimetervalue = FloatField('Mean Perimeter', validators=[DataRequired()])
    meanareavalue = FloatField('Mean Area', validators=[DataRequired()])
    meansmoothnessvalue = FloatField('Mean Smoothness', validators=[DataRequired()])
    meancompactnessvalue = FloatField('Mean Compactness', validators=[DataRequired()])
    meanconcavityvalue = FloatField('Mean Concavity', validators=[DataRequired()])
    meanconcavepointsvalue = FloatField('Mean Concave Points', validators=[DataRequired()])
    meansymmetryvalue = FloatField('Mean Symmetry', validators=[DataRequired()])
    meanfractaldimensionvalue = FloatField('Mean Fractal Dimension', validators=[DataRequired()])
    radiuserrorvalue = FloatField('Radius Error', validators=[DataRequired()])
    textureerrorvalue = FloatField('Texture Error', validators=[DataRequired()])
    perimetererrorvalue = FloatField('Perimeter Error', validators=[DataRequired()])
    areaerrorvalue = FloatField('Area Error', validators=[DataRequired()])
    smoothnesserrorvalue = FloatField('Smoothness Error', validators=[DataRequired()])
    compactnesserrorvalue = FloatField('Compactness Error', validators=[DataRequired()])
    concavityerrorvalue = FloatField('Concavity Error', validators=[DataRequired()])
    concavepointserrorvalue = FloatField('Concave Points Error', validators=[DataRequired()])
    symmetryerrorvalue = FloatField('Symmetry Error', validators=[DataRequired()])
    fractaldimensionerrorvalue = FloatField('Fractal Dimension Error', validators=[DataRequired()])
    worstradiusvalue = FloatField('Worst Radius', validators=[DataRequired()])
    worsttexturevalue = FloatField('Worst Texture', validators=[DataRequired()])
    worstperimetervalue = FloatField('Worst Perimeter', validators=[DataRequired()])
    worstareavalue = FloatField('Worst Area', validators=[DataRequired()])
    worstsmoothnessvalue = FloatField('Worst Smoothness', validators=[DataRequired()])
    worstcompactnessvalue = FloatField('Worst Compactness', validators=[DataRequired()])
    worstconcavityvalue = FloatField('Worst Concavity', validators=[DataRequired()])
    worstconcavepointsvalue = FloatField('Worst Concave Points', validators=[DataRequired()])
    worstsymmetryvalue = FloatField('Worst Symmetry', validators=[DataRequired()])
    worstfractaldimensionvalue = FloatField('Worst Fractal Dimension', validators=[DataRequired()])

    diagnose = SubmitField('Diagnose')