from flask_wtf import Form
from wtforms import DecimalField, PasswordField, SubmitField
from wtforms.validators import  DataRequired, Email

class TextForm(Form):
    meanradiusvalue = DecimalField('meanradiusvalue', validators=[DataRequired()])
    meantexturevalue = DecimalField('meantexturevalue', validators=[DataRequired()])
    meanperimetervalue = DecimalField('meanperimetervalue', validators=[DataRequired()])
    meanareavalue = DecimalField('meanareavalue', validators=[DataRequired()])
    meansmoothnessvalue = DecimalField('meansmoothnessvalue', validators=[DataRequired()])
    meancompactnessvalue = DecimalField('meancompactnessvalue', validators=[DataRequired()])
    meanconcavityvalue = DecimalField('meanconcavityvalue', validators=[DataRequired()])
    meanconcavepointsvalue = DecimalField('meanconcavepointsvalue', validators=[DataRequired()])
    meansymmetryvalue = DecimalField('meansymmetryvalue', validators=[DataRequired()])
    meanfractaldimensionvalue = DecimalField('meanfractaldimensionvalue', validators=[DataRequired()])
    radiuserrorvalue = DecimalField('radiuserrorvalue', validators=[DataRequired()])
    textureerrorvalue = DecimalField('textureerrorvalue', validators=[DataRequired()])
    perimetererrorvalue = DecimalField('perimetererrorvalue', validators=[DataRequired()])
    areaerrorvalue = DecimalField('areaerrorvalue', validators=[DataRequired()])
    smoothnesserrorvalue = DecimalField('smoothnesserrorvalue', validators=[DataRequired()])
    compactnesserrorvalue = DecimalField('compactnesserrorvalue', validators=[DataRequired()])
    concavityerrorvalue = DecimalField('concavityerrorvalue', validators=[DataRequired()])
    concavepointserrorvalue = DecimalField('concavepointserrorvalue', validators=[DataRequired()])
    symmetryerrorvalue = DecimalField('symmetryerrorvalue', validators=[DataRequired()])
    fractaldimensionerrorvalue = DecimalField('fractaldimensionerrorvalue', validators=[DataRequired()])
    worstradiusvalue = DecimalField('worstradiusvalue', validators=[DataRequired()])
    worsttexturevalue = DecimalField('worsttexturevalue', validators=[DataRequired()])
    worstperimetervalue = DecimalField('worstperimetervalue', validators=[DataRequired()])
    worstareavalue = DecimalField('worstareavalue', validators=[DataRequired()])
    worstsmoothnessvalue = DecimalField('worstsmoothnessvalue', validators=[DataRequired()])
    worstcompactnessvalue = DecimalField('worstcompactnessvalue', validators=[DataRequired()])
    worstconcavityvalue = DecimalField('worstconcavityvalue', validators=[DataRequired()])
    worstconcavepointsvalue = DecimalField('worstconcavepointsvalue', validators=[DataRequired()])
    worstsymmetryvalue = DecimalField('worstsymmetryvalue', validators=[DataRequired()])
    worstfractaldimensionvalue = DecimalField('worstfractaldimensionvalue', validators=[DataRequired()])

    diagnose = SubmitField('Diagnose')